package tombenpotter.icarus.reference;

import cpw.mods.fml.common.ModMetadata;

import java.util.Arrays;

public class Metadata
{
    public static ModMetadata init(ModMetadata metadata)
    {
        metadata.modId = Reference.ID;
        metadata.name = Reference.NAME;
        metadata.description = "Wings, the not easy way!";
        metadata.url = "http://minecraft.curseforge.com/mc-mods/235702-tombenpotters-icarus";
        metadata.version = Reference.VERSION;
        metadata.authorList = Arrays.asList("tombenpotter");
        metadata.credits = "GustoniaEagle, for the cool textures!";
        metadata.autogenerated = false;
        return metadata;
    }
}
